"""
Pydantic schemas for the Hospital Workflow Automation System.

Defines all data contracts used across layers:
- API request/response models
- Planner output (WorkflowPlan)
- A2A messaging format
- MCP tool call records
- Execution logging
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ─────────────────────────────────────────────
# API Models
# ─────────────────────────────────────────────

class AdmitPatientRequest(BaseModel):
    """Input payload for the /admit_patient endpoint."""
    patient_id: int = Field(..., description="Unique patient identifier")


class GenericEventRequest(BaseModel):
    """
    Generic event trigger — allows ANY event to be sent into the system.
    This ensures the planner is truly dynamic and not tied to a single endpoint.
    """
    event: str = Field(..., description="Event type, e.g. 'patient_admitted', 'lab_results_ready'")
    context: Dict[str, Any] = Field(default_factory=dict, description="Event context/payload")


# ─────────────────────────────────────────────
# Planner Models
# ─────────────────────────────────────────────

class TaskPlan(BaseModel):
    """
    A single task in a workflow plan.
    The planner generates a list of these dynamically based on the event.
    """
    task_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8], description="Unique task ID")
    task: str = Field(..., description="Task type, e.g. 'fetch_patient_data', 'assign_doctor'")
    agent: str = Field(..., description="Target agent name, e.g. 'DataAgent'")
    params: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the task")
    depends_on: Optional[str] = Field(None, description="Task ID this depends on (for ordering)")
    priority: int = Field(default=1, description="Priority level (1=highest)")


class WorkflowPlan(BaseModel):
    """
    Complete workflow plan generated by the Planner.
    Contains the triggering event and an ordered list of tasks.
    """
    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique plan ID")
    event: str = Field(..., description="The event that triggered this plan")
    context: Dict[str, Any] = Field(default_factory=dict, description="Event context")
    tasks: List[TaskPlan] = Field(..., description="Ordered list of tasks to execute")
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ─────────────────────────────────────────────
# A2A (Agent-to-Agent) Communication Models
# ─────────────────────────────────────────────

class A2AMessage(BaseModel):
    """
    Structured message for inter-agent communication.
    
    Flow:
    1. Agent A creates message with from_agent, to_agent, request, payload
    2. Orchestrator routes message to Agent B
    3. Agent B processes and fills in the response field
    4. Message is returned to Agent A
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Message UUID")
    from_agent: str = Field(..., description="Sending agent name")
    to_agent: str = Field(..., description="Receiving agent name")
    request: str = Field(..., description="Request type, e.g. 'get_patient_department'")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Request data")
    response: Optional[Dict[str, Any]] = Field(None, description="Response from receiving agent")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    status: str = Field(default="pending", description="Message status: pending, delivered, responded, failed")


# ─────────────────────────────────────────────
# MCP (Model Context Protocol) Models
# ─────────────────────────────────────────────

class MCPToolCall(BaseModel):
    """
    Record of a tool invocation through the MCP layer.
    Agents NEVER access DB/services directly — they go through MCP.
    """
    call_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    tool_name: str = Field(..., description="Name of the MCP tool called")
    params: Dict[str, Any] = Field(default_factory=dict, description="Parameters passed to the tool")
    result: Optional[Any] = Field(None, description="Result returned by the tool")
    caller_agent: str = Field(default="", description="Which agent made the call")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    success: bool = Field(default=True)
    error: Optional[str] = Field(None)


# ─────────────────────────────────────────────
# Execution Logging Models
# ─────────────────────────────────────────────

class StepLog(BaseModel):
    """Log of a single execution step within a workflow."""
    step_number: int
    task_id: str
    task: str
    agent: str
    status: str = Field(default="pending", description="pending, running, completed, failed")
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    duration_ms: Optional[float] = None
    tool_calls: List[MCPToolCall] = Field(default_factory=list)
    a2a_messages: List[A2AMessage] = Field(default_factory=list)
    result: Optional[Any] = None
    error: Optional[str] = None


class ExecutionLog(BaseModel):
    """Complete execution log for a workflow run."""
    execution_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    plan_id: str
    event: str
    status: str = Field(default="running", description="running, completed, partial_failure, failed")
    steps: List[StepLog] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    total_duration_ms: Optional[float] = None


# ─────────────────────────────────────────────
# Agent Capability Registration
# ─────────────────────────────────────────────

class AgentCapability(BaseModel):
    """Describes what an agent can do — used by the planner to route tasks."""
    agent_name: str
    capabilities: List[str] = Field(..., description="List of task types this agent handles")
    description: str = Field(default="")
