"""PDF generator for appointment confirmation letters."""

from __future__ import annotations

from io import BytesIO
from typing import Mapping, Any

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def build_appointment_letter_pdf(
    appointment: Mapping[str, Any],
    patient_name: str,
    doctor_name: str,
) -> bytes:
    """Render a simple appointment letter as PDF bytes."""
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    top = height - 72

    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(72, top, "Hospital Workflow Automation")

    pdf.setFont("Helvetica", 11)
    pdf.drawString(72, top - 20, "Appointment Confirmation Letter")

    pdf.setLineWidth(0.5)
    pdf.line(72, top - 28, width - 72, top - 28)

    lines = [
        f"Confirmation Code: {appointment.get('confirmation_code', '-')}",
        f"Appointment ID: {appointment.get('id', '-')}",
        f"Patient Name: {patient_name}",
        f"Doctor Name: {doctor_name}",
        f"Department: {appointment.get('department', '-')}",
        f"Start Time: {appointment.get('appointment_start', '-')}",
        f"End Time: {appointment.get('appointment_end', '-')}",
        f"Status: {appointment.get('status', '-')}",
    ]

    y = top - 58
    for line in lines:
        pdf.drawString(72, y, line)
        y -= 20

    note = (
        "Please arrive at least 15 minutes before your appointment time. "
        "Bring a valid photo ID and your insurance details."
    )
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(72, y - 10, note)

    pdf.setFont("Helvetica", 9)
    pdf.drawString(72, 60, "Generated by Hospital Workflow Automation")

    pdf.showPage()
    pdf.save()

    buffer.seek(0)
    return buffer.getvalue()
