services:
  # FastAPI Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: on-failure
